### PR TITLE
Implement entry flow animations and app icon

### LINKED ISSUE #22: Entry Flow Animations and App Icon

### PR DESCRIPTION
**Pull request by ThunderRoar**
- Implement animation design for landing page
- Change the mobile app logo
- Implement transition animation from both customer login and create account to mall view
- Implement transition animation from vendor login and create account to store view
- Adjust unit tests after animation implementations for vendor modules
- Implement notifications for new product additions for vendors

### CODE REVIEW

**Review by murphylee10 — APPROVED** [review]
w anims

**Comment by ThunderRoar** [comment]
IMPORTANT NOTE:
Make sure to go to the top tool bar in android studio and follow these instructions.

1. Build > Clean Project
2. Build > Rebuild Project
3. Run the project on the emulator or physical device

The above ensures that saved cashe would be wiped clean before rebuilding the project app with the new implementations.

**Review by jang-35 — APPROVED** [review]
SHAISHHHHH

**Comment by jang-35** [comment]
thats my goat

**Review by danielalyoshin — APPROVED** [review]
Awesome!

**Pull request merged**
