### PR TITLE
Implement customer order history

### LINKED ISSUE #10: As a shopper, I should be able to select my previous orders and get a status as to whether or not the store has completed it so that I can stay informed about its progress.

### PR DESCRIPTION
**Pull request by jang-35**
- Implement customer order history for cart orders and direct purchases, sorted by date and status
- Implement pending/completed flag on order card
- Implement drop-down for order breakdown

### CODE REVIEW

**Review by ThunderRoar — COMMENTED** [review]
There definitely UI fixes to be done for the product page. The customer login page does not work due to pass of null object.

**Review by murphylee10 — APPROVED** [review]
lgtm (not 4 points)

**Review by ThunderRoar — APPROVED** [review]
Last issue done!

**Review by danielalyoshin — APPROVED** [review]
👍

**Pull request merged**
